---
title: "Make the prediction grid"
author: "Max Lindmark"
date: today
date-format: iso
toc: true
format: 
  html:
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
editor: source
---

## Intro
Make an evenly spaced UTM prediction grid with all spatially varying covariates for the diet and the biomass data

```{r lib}
#| message: false

library(tidyverse)
library(tidylog)
library(tidync)
library(tidyterra)
library(sp)
library(devtools)
library(RCurl)
library(sdmTMB)
library(ncdf4)
library(terra)
library(viridis)
library(marmap)
library(crayon)
# devtools::install_github("seananderson/ggsidekick") # not on CRAN
library(ggsidekick)
theme_set(theme_sleek())

home <- here::here()

for (fun in list.files(paste0(home, "/R/functions"))) {
  source(paste(home, "R/functions", fun, sep = "/"))
}
```

Read data and depth-raster

```{r data}
# Read data
d <- readr::read_csv(paste0(home, "/data/clean/larval_size.csv"))
```

## Make the grid
First make a grid for the area, then subset that based on the extend of the size data

```{r make pred grid}
x <- d$X
y <- d$Y
z <- chull(x, y)

coords <- cbind(x[z], y[z])

coords <- rbind(coords, coords[1, ])

plot(coords[, 1] ~ coords[, 2]) # plot data

sp_poly <- sp::SpatialPolygons(
  list(sp::Polygons(list(sp::Polygon(coords)), ID = 1))
)

sp_poly_df <- sp::SpatialPolygonsDataFrame(sp_poly,
  data = data.frame(ID = 1)
)
cell_width <- 3

pred_grid <- expand.grid(
  X = seq(min(d$X), max(d$X), cell_width),
  Y = seq(min(d$Y), max(d$Y), cell_width),
  year = seq(min(d$year), max(d$year))
)

ggplot(pred_grid |> filter(year == 2019), aes(X, Y)) +
  geom_point(size = 0.1) +
  theme_void() +
  coord_sf()

sp::coordinates(pred_grid) <- c("X", "Y")

inside <- !is.na(sp::over(pred_grid, as(sp_poly_df, "SpatialPolygons")))

pred_grid <- pred_grid[inside, ]

pred_grid <- as.data.frame(pred_grid)

plot_map +
  geom_point(data = filter(pred_grid, year == 1999), aes(X * 1000, Y * 1000), size = 0.001, alpha = 0.5) +
  NULL

# Add lat and lon
# Need to go from UTM to lat long for this one...
# https://stackoverflow.com/questions/30018098/how-to-convert-utm-coordinates-to-lat-and-long-in-r
xy <- as.matrix(pred_grid |> dplyr::select(X, Y) |> mutate(X = X * 1000, Y = Y * 1000))
v <- vect(xy, crs = "+proj=utm +zone=32 +datum=WGS84  +units=m")
y <- project(v, "+proj=longlat +datum=WGS84")
lonlat <- geom(y)[, c("x", "y")]

pred_grid$lon <- lonlat[, 1]
pred_grid$lat <- lonlat[, 2]
```

### Depth and crop

```{r}
## Generate a depth box containing the bathymetries.
depth_box <- getNOAA.bathy(min(d$lon) - .1, max(d$lon) + .1, min(d$lat) - .1, max(d$lat) + .1)

pred_grid$depth <- get.depth(depth_box, x = pred_grid$lon, y = pred_grid$lat, locator = F)$depth

## Convert to strictly positive values.
pred_grid$depth <- pred_grid$depth * (-1)

plot_map +
  geom_raster(
    data = pred_grid,
    aes(X * 1000, Y * 1000, fill = depth)
  ) +
  geom_sf()

# extractCovariateAtLocation(
#   "elevation", # Name of the covariate to extract. One of: sst, chlorophyll, elevation
#   pred_grid, # A df containing the set locations to be evaluated.
#   dep_raster,
#   changesYearly = 0,
#   nametocov = "depth2",
#   messages = 1
# )

# Remove Denmanrk...
pred_grid <- pred_grid |>
  mutate(keep = ifelse(lat < 57.103 & lon < 10.28, "N", "Y")) |>
  filter(keep == "Y") |>
  dplyr:::select(-keep)

plot_map +
  geom_raster(
    data = pred_grid,
    aes(X * 1000, Y * 1000, fill = depth)
  ) +
  geom_sf()
```

## Add in dynamic covariates

```{r}
covPath <- paste0(home, "/data/covariates")
```

## Ensemble

```{r}
read_trim_nc <- function(file_path){
  
  tidync(file_path) |>
    hyper_tibble() |>
    mutate(date = as.Date(time, origin = "1993-01-01"),
           year = year(date),
           month = month(date),
           day = day(date),
           year = year(date)) |> 
    filter(year <= 2024 & month == 1 & day == 1 & lon > 7 & lon < 15 & lat > 54 & lat < 61 & percentiles == 50)
}
```

```{r}
# Here are the data: https://zenodo.org/records/6523926
print(nc_open(paste0(home, "/data/covariates/ensemble/thetao_ensemble_sd+ba_surface_depth_5.0_perc_ssp245.nc")))

st_tibble5 <- read_trim_nc(paste0(home, "/data/covariates/ensemble/thetao_ensemble_sd+ba_surface_depth_5.0_perc_ssp245.nc"))
#st_tibble25 <- read_trim_nc(paste0(home, "/data/covariates/ensemble/thetao_ensemble_sd+ba_surface_depth_25.0_perc_ssp245.nc"))
#st_tibblebot <- read_trim_nc(paste0(home, "/data/covariates/ensemble/thetao_ensemble_sd+ba_bottom_perc_ssp245.nc"))

# Average temperature across depths
# st_tibble <- bind_rows(st_tibble5 |> mutate(depth = "5"),
#                        #st_tibble25 |> mutate(depth = "25")#,
#                        #st_tibblebot |> mutate(depth = "bottom")
#                        ) |> 
#   summarise(thetao = mean(thetao), .by = c(lon, lat, time, date, year, month, day))

# Loop through all year combos, extract the temperatures at the data locations
temp_list <- list()

for (i in unique(pred_grid$year)) {
  d_sub <- filter(pred_grid, year == i)
  temp_tibble_sub <- filter(st_tibble5, year == i)

  # Convert to raster
  temp_raster <- as_spatraster(temp_tibble_sub,
    xycols = 3:4,
    crs = "WGS84", digits = 3
  )

  # Extract from raster
  d_sub$temp <- terra::extract(
    temp_raster$thetao,
    d_sub |> dplyr::select(lon, lat)
  )$thetao

  # Save
  temp_list[[i]] <- d_sub
}

d_temp <- bind_rows(temp_list)

# Chlorophyll - continue with d_temp
print(nc_open(paste0(home, "/data/covariates/ensemble/chl_ensemble_sd+ba_surface_depth_5.0_perc_ssp245.nc")))

ch_tibble5 <- read_trim_nc(paste0(home, "/data/covariates/ensemble/chl_ensemble_sd+ba_surface_depth_5.0_perc_ssp245.nc"))

# Loop through all year combos, extract the temperatures at the data locations
ch_list <- list()

for (i in unique(d_temp$year)) {
  d_sub <- filter(d_temp, year == i)
  ch_tibble_sub <- filter(ch_tibble5, year == i)

  # Convert to raster
  ch_raster <- as_spatraster(ch_tibble_sub,
    xycols = 3:4,
    crs = "WGS84", digits = 3
  )

  # Extract from raster
  d_sub$chl <- terra::extract(
    ch_raster$chl,
    d_sub |> dplyr::select(lon, lat)
  )$chl

  mean(d_sub$chl, na.rm = TRUE)
  
  # Save
  ch_list[[i]] <- d_sub
}

d_chl <- bind_rows(ch_list)

# Convert to mg/m3
d_chl$chl <- d_chl$chl*1000000
```

## Save

```{r save}
pred_grid <- d_chl |> drop_na(temp)

write_csv(pred_grid, file = paste0(home, "/data/clean/pred_grid.csv"))
```
