---
title: "Fit density models"
author: "Max Lindmark"
date: today
date-format: iso
toc: true
format: 
  html:
    page-layout: full
    embed-resources: true
knitr: 
  opts_chunk:
    fig.align: center
    out-width: 100%
editor: source
---

```{r load libraries}
#| message: false
#| warning: false

# Load libraries
library(tidyverse)
library(tidylog)
library(sdmTMB)
library(patchwork)
library(viridis)
library(RColorBrewer)
library(modelr)
library(ggstats)
library(ggspatial)
library(ggsidekick)
theme_set(theme_sleek())

home <- here::here()
source(paste0(home, "/R/functions/map-plot.R"))
```

Read data and prediction grid, scale variables

```{r data}
#| message: false

# Read data
d <- readr::read_csv(paste0(home, "/data/clean/larval_density.csv")) |>
  mutate(
    yday_ct = yday - mean(yday),
    year_f = as.factor(year),
    species_f = as.factor(species),
    year_ct = year - median(year),
    depth_sc = (depth - mean(depth)) / sd(depth)
  ) |>
  drop_na(no_m2)

length(unique(d$haul_id))

l <- readr::read_csv(paste0(home, "/data/clean/larval_size.csv")) 

length(unique(l$haul_id))

# The reason haul id's differ is because not all densities could be standardized!
l2 <- l |>
  left_join(d |> dplyr::select(no_m2, haul_id, species),
            by = c("haul_id", "species"))
```



